### ISSUE TITLE
Dashboard infinite getTeams fetch loop

### ISSUE THREAD

**Issue by detj** [measure-sh/measure#1281]
## Summary

DashboardLayout gets into an infinite getTeams fetch loop, when `sessionStorage` has selected app and selected date range set. This issue happens regardless of nextjs's `reactStrictMode` config whether it is true or false.

![image](https://github.com/user-attachments/assets/53113266-a540-46c7-b133-9b562c347be2)

Additionally, it seems the `throw` statement in [time_utils.ts](https://github.com/measure-sh/measure/blob/3f3c42fa74f6bccddf4dfb10a08ae19b29bbf7a9/frontend/dashboard/app/utils/time_utils.ts#L43) could be contributing to this condition. When execution encounters a `throw` and there is no React ErrorBoundary that catches and handles the error, [the empty dependency `useEffect`](https://github.com/measure-sh/measure/blob/3f3c42fa74f6bccddf4dfb10a08ae19b29bbf7a9/frontend/dashboard/app/%5BteamId%5D/layout.tsx#L81) nullifies and leads to the `getTeams` call on every render.

## Steps to reproduce

1. Open `http://localhost:3000/:teamId/overview` and open browser dev tools
2. Simulate the following sessionStorage values by running this in your browser dev tools console

    ```js
    sessionStorage.setItem("measurePersistedFilters", JSON.stringify({
      "selectedAppId": "c8f2584b-4fe4-43e1-94f4-f3f80c61ce40",
      "selectedDateRange": "Last Year",
      "selectedStartDate": "2023-09-23T20:12:57.175+05:30",
      "selectedEndDate": "2024-09-23T20:12:57.175+05:30"
    }));
    ```
    
   - This achieves the same effect as if the user has selected an app and date range filters.
   - The `selectedAppId` value will be different for each instance, but as long as the sessionStorage has data of the above shape, the infinite data fetching loop occurs.
3. Refresh the page
4. Inspect browser dev tool's network panel and console for the repeating fetch calls to `getTeams`

## Version

Measure v0.1.1+

**Comment by anupcowkur** [comment]
the keys of the persisted filters have changed in a recent commit. 

the structure should now be:

```
appId: "e963e98a-aca9-4bab-bd62-70a74801384e"
dateRange: "Last 6 Months"
endDate: "2024-09-24T16:55:53.830+05:30"
startDate: "2024-03-24T16:55:53.830+05:30"
```

note that the `selected` part has been removed.

The issue occurs when you are on a commit before the naming change and update to a commit with the naming change and reload the page. In this case, it looks for the new name and doesn't find and throws a downstream error leading to the loop.

The fix is to just open a new tab so the session storage is cleared out. Also, once we move to url params instead of session storage in #1217, this will not happen even on name change.
